version: 2

project_name: ciptr-cli

before:
  hooks:
    - go mod tidy -C cli

builds:
  - id: ciptr-cli
    dir: cli
    binary: ciptr-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/guerrieroriccardo/CIPTr/cli/internal/version.Version={{.Version}}
      - -X github.com/guerrieroriccardo/CIPTr/cli/internal/version.Commit={{.ShortCommit}}
      - -X github.com/guerrieroriccardo/CIPTr/cli/internal/version.Date={{.Date}}

archives:
  - id: ciptr-cli
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "Refactoring"
      regexp: "^refactor"
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^chore"
      - "^docs"
      - "^ci"

release:
  github:
    owner: guerrieroriccardo
    name: CIPTr
