services:
  postgres:
    container_name: ciptr-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciptr"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: ciptr-backend
    image: guerrieroriccardo/ciptr-backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable}
      PORT: ${PORT:-8080}
      GIN_MODE: ${GIN_MODE:-release}
      JWT_SECRET: ${JWT_SECRET}
      LABEL_BASE_URL: ${LABEL_BASE_URL:-}
      LABEL_LOGO_PATH: ${LABEL_LOGO_PATH:-/app/logo.png}
    volumes:
        
    depends_on:
      postgres:
        condition: service_healthy

  # frontend service will be added in a later step

